### ISSUE TITLE
content on empty "TO DO" page

### ISSUE THREAD

**Issue by shiffman** [shiffman/icm.shiffman.net#7]
@scottgarner is this not correct?  (I don't see 'TO DO')

https://github.com/shiffman/icm.shiffman.net/blob/gh-pages/_posts/2013-08-29-5.3.html
http://icm.shiffman.net/5.3/

**Comment by scottgarner** [comment]
Currently, everything in the body of a given post ends up in a div called `annotations`, which is set to `display: none` in the css. When the page loads, a script looks at everything in annotations with data-start and data-end attributes and feeds them to Popcorn.

We could definitely add a method to view all annotations at once or come up with some other means to store notes.

**Comment by shiffman** [comment]
great, i'll leave this open as i think this could be useful to have posts without videos/annotations, but it's low priority.

**Comment by scottgarner** [comment]
It would be pretty trivial to have different categories use different templates and we could also have a kind of published/draft behavior, so just let me know what works best for you.

**Comment by shiffman** [comment]
I just made a quick and dirty layout for the todo pages.  See 01d899e570b053558e3ee1636f4f3c2dd9c1db34.  @scottgarner feel free to make any improvements as you see fit.  In theory I might want to write custom content on individual pages, but for now this will work fine.

**Comment by scottgarner** [comment]
I made a few little tweaks and added support for custom content in that the body of todo pages gets flowed into the the template, but that may not be what you meant?

http://icm.shiffman.net/8.7/

**Comment by shiffman** [comment]
perfect, thanks!
